### ISSUE TITLE
Customer Panel 'View Order' shows 'Checkout' version of Payment Title

### ISSUE THREAD

**Issue by Entreprende** [EmilEriksen/woocommerce-pay-title#1]
As stated in the title, the title of the Payment method on the Checkout page in WooCommerce works fantastic. When a user goes to review their order information on their own Dashboard backend the 'different' Title from the Checkout section of the site persists to showing the same value on the customer order review page.

I would like to show the same / 'normal' Payment Method Title (as what is shown in the admin back end) on the customer order review page.

You can see the 'failure' at the following link:

http://i.imgur.com/iHb9dEi.png

What's the best way to ensure that the 'normal' title for the payment method is shown differently on the Checkout page, yet defaults to the internal/admin version on the user's order review page / everywhere else?

Thank you very much for making this possible in the first place. Much appreciated. I appreciate collaboration on 'improving' the function of this plugin even more.

Edit: Happy Thanksgiving ;)

**Comment by EmilEriksen** [comment]
I'm glad you like the plugin. Thank you for your kind words!

This definitely isn't expected behaviour. Unfortunately I wasn't able to reproduce the bug. Since the payment method title is saved to the DB when an order is created the only way this should be possible (unless something really funky is going on) is if the checkout title was saved to the DB. In this case you would only see the checkout title of the payment method everywhere. Could you provide me with some more info?:

- Your WC version
- Does it happen with all payment methods or just that one?
- Do you see the normal payment method title on the thank you page on orders where this happens?
- Does it still happen if you try to switch themes?

Happy Thanksgiving to you too!

**Comment by Entreprende** [comment]
You are absolutely correct sir. Ran a test transaction again and the correct name used in the Admin End persisted to the User Dashboard. Sorry to waste your time today!

Cheers from the USA!
